In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [4]:
nodes = [ "White", "Blue"]
trans_matrix = np.array([[0.7,0.3],[0.6,0.4]])
df = pd.DataFrame(trans_matrix,columns=nodes,index=nodes)
trans_matrix

array([[0.7, 0.3],
       [0.6, 0.4]])

In [5]:
#state = np.array([1,0])
state = np.array([0.5,0.5])

In [6]:
np.matmul

<ufunc 'matmul'>

In [7]:
Mon = np.matmul(state , trans_matrix)

In [8]:
Mon

array([0.65, 0.35])

In [9]:
Tue = np.matmul(Mon, trans_matrix)
Tue

array([0.665, 0.335])

In [10]:
np.matmul

<ufunc 'matmul'>